#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=https://swirrl.climate4impact.eu/swirrl/jupyter/784edd54-fc2e-4f81-bca4-3011d821231a
SERVICE_ID=784edd54-fc2e-4f81-bca4-3011d821231a
get_notebook http://swirrl-api/swirrl-api/v1.0/notebook d9a1a1d2-5842-4875-b41c-20de5dcc7632 784edd54-fc2e-4f81-bca4-3011d821231a
mkdir -p ~/data/staginghistory/stage.00009
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/swirrl_fileinfo.json ~/data/staginghistory/stage.00009/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20390101-20391231.nc ~/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20390101-20391231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc ~/data/staginghistory/stage.00009/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00009/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00008
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00008/swirrl_fileinfo.json ~/data/staginghistory/stage.00008/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00009//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00008/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00009//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc ~/data/staginghistory/stage.00008/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20240101-20241231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00009//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00008/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00009//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc ~/data/staginghistory/stage.00008/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc
ln ~/data/staginghistory/stage.00009//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00008/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00007
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/swirrl_fileinfo.json ~/data/staginghistory/stage.00007/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00008//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00007/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00008//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00007/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00008//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc ~/data/staginghistory/stage.00007/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_21000101-21001231.nc
ln ~/data/staginghistory/stage.00008//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00007/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00006
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00006/swirrl_fileinfo.json ~/data/staginghistory/stage.00006/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00007//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00006/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00007//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00006/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00007//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00006/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00005
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00005/swirrl_fileinfo.json ~/data/staginghistory/stage.00005/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00006//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00005/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00006//pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00005/pr_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00006//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00005/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00004
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00004/swirrl_fileinfo.json ~/data/staginghistory/stage.00004/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20900101-20901231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00005//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00004/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00003
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/swirrl_fileinfo.json ~/data/staginghistory/stage.00003/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00004//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00003/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00002
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20820101-20821231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20810101-20811231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00003//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00002/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
mkdir -p ~/data/staginghistory/stage.00001
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20170101-20171231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20220101-20221231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20190101-20191231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20200101-20201231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20150101-20151231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20180101-20181231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20210101-20211231.nc
ln ~/data/staginghistory/stage.00002//tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc ~/data/staginghistory/stage.00001/tasmax_day_EC-Earth3_ssp585_r1i1p1f1_gr_20160101-20161231.nc
ln -s ~/data/staginghistory/stage.00009 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://swirrl-api/swirrl-api/v1.0/notebook
